CREATE TABLE `product` (
  `id`         BIGINT(20) NOT NULL AUTO_INCREMENT,
  `name`    VARCHAR (255) NOT NULL,
  `price`      DOUBLE(20, 3) NOT NULL,
  PRIMARY KEY (id)
) ENGINE =INNODB DEFAULT CHARSET =latin1;
